version: '3'
services:
  web:
    build: .
    ports:
     - "8080:8080"
    depends_on: 
     - redis
  redis:
    image: "redis:alpine"
db:
    image: postgres:9.6
    container_name: "postgres"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432